// <auto-generated />
namespace PhoneApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InitLasttt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitLasttt));
        
        string IMigrationMetadata.Id
        {
            get { return "202001201925191_InitLasttt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
