namespace PhoneApp.Migrations
{
    using PhoneApp.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<PhoneApp.Models.smartPhonesDb>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            ContextKey = "PhoneApp.Models.smartPhonesDb";
        }

        protected override void Seed(PhoneApp.Models.smartPhonesDb context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.

            Manufacturer m1 = new Manufacturer { name = "Alcatel", country = "France" };
            Manufacturer m2 = new Manufacturer { name = "Apple", country = "California" };
            Manufacturer m3 = new Manufacturer { name = "CAT", country = "America" };
            Manufacturer m4 = new Manufacturer { name = "Huawei", country = "China" };
            Manufacturer m5 = new Manufacturer { name = "Lenovo", country = "China" };
            Manufacturer m6 = new Manufacturer { name = "Motorola", country = "America" };
            Manufacturer m7 = new Manufacturer { name = "LG", country = "South Korea" };
            Manufacturer m8 = new Manufacturer { name = "Nokia", country = "Finnish" };
            Manufacturer m9 = new Manufacturer { name = "Samsung", country = "South Korea" };
            Manufacturer m10 = new Manufacturer { name = "Sony Mobile", country = "Japan" };
            Manufacturer m11 = new Manufacturer { name = "Xiaomi", country = "China" };

            context.Manufacturers.AddOrUpdate(m1, m2, m3, m4, m5, m6, m7, m8, m9, m10, m11);

            context.Phones.AddOrUpdate(new Phone { name = "Galaxy A70", description = "Samsung Galaxy A70 supports frequency bands GSM , HSPA , LTE. Official announcement date is March 2019. The device is working on an Android 9.0 (Pie) with a Octa-core (2x2.0 GHz & 6x1.7 GHz) processor and 6/8 GB RAM memory. Samsung Galaxy A70 has 128 GB of internal memory. The main screen size is displaysize6.7 inches, 108.4 cm2 with 1080 x 2400 pixels resolution. It has a 393 ppi density) ppi pixel density. The screen covers about 86.0% of the device's body. This screen to body ratio is a very impressive Versions: SM-A705F/DS (Global); SM-A7050 (China)", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.tgdd.vn%2FProducts%2FImages%2F42%2F195012%2Fsamsung-galaxy-a70-black-400x460.png&f=1&nofb=1", price = 400, review = 0, manufacturer = m9 });
            context.Phones.AddOrUpdate(new Phone { name = "1X (2019)", description = "Alcatel 1x (2019) supports frequency bands GSM , HSPA , LTE. Official announcement date is January 2019. The device is working on an Android 8.1 (Oreo) with a Quad-core 1.5 GHz Cortex-A53 processor and 2 GB RAM memory. Alcatel 1x (2019) has 16 GB of internal memory. This device has a Mediatek MT6739 (28 nm) chipset. The main screen size is displaysize5.5 inches, 78.1 cm2 with 720 x 1440 pixels, 18:9 ratio resolution. It has a 293 ppi density) ppi pixel density. The screen covers about 77.5% of the device's body. This screen to body ratio is a very impressive", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Frawdev.com.ng%2Fblog%2Fwp-content%2Fuploads%2F2019%2F04%2FAlcatel-3-2019.png&f=1&nofb=1", price = 70, review = 0, manufacturer =  m1});
            context.Phones.AddOrUpdate(new Phone { name = "iPhone 11", description = "Apple iPhone 11 supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is September 2019. The device is working on an iOS 13 with a Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder) processor. Apple iPhone 11 has 64GB 4GB RAM, 128GB 4GB RAM, 256GB 4GB RAM of built-in memory. This device has a Apple A13 Bionic (7 nm+) chipset. The main screen size is displaysize6.1 inches, 90.3 cm2 with 828 x 1792 pixels, 19.5:9 ratio resolution. It has a 326 ppi density) ppi pixel density. The screen covers about 79.0% of the device's body. This screen to body ratio is a very impressive ALL VERSIONS A2221A2111A2223 Versions: A2221 (Global market) A2111 (USA, Canada, Puerto Rico, U.S. Virgin Islands) A2223 (China, Hong Kong)", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fss7.vzw.com%2Fis%2Fimage%2FVerizonWireless%2FApple_iPhone_11_Red_09102019_b%3F%24png8alpha256%24%26hei%3D520&f=1&nofb=1", price = 750, review = 0, manufacturer = m2 });
            context.Phones.AddOrUpdate(new Phone { name = "iPhone 11 Pro", description = "Apple iPhone 11 Pro supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is September 2019. The device is working on an iOS 13 with a Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder) processor. Apple iPhone 11 Pro has 64GB 4GB RAM, 256GB 4GB RAM, 512GB 4GB RAM of built-in memory. This device has a Apple A13 Bionic (7 nm+) chipset. The main screen size is displaysize5.8 inches, 84.4 cm2 with 1125 x 2436 pixels, 19.5:9 ratio resolution. It has a 458 ppi density) ppi pixel density. The screen covers about 82.1% of the device's body. This screen to body ratio is a very impressive ALL VERSIONS A2215A2160A2217 Versions: A2215 (Global market) A2160 (USA, Canada, Puerto Rico, U.S. Virgin Islands) A2217 (China, Hong Kong)", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fss7.vzw.com%2Fis%2Fimage%2FVerizonWireless%2FiPhone_11_Pro_Max_all_5up%3F%24png8alpha256%24%26hei%3D520&f=1&nofb=1", price = 1100, review = 0, manufacturer =  m2});
            context.Phones.AddOrUpdate(new Phone { name = "iPhone 11 Pro Max", description = "Apple iPhone 11 Pro Max supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is September 2019. The device is working on an iOS 13 with a Hexa-core (2x2.65 GHz Lightning + 4x1.8 GHz Thunder) processor. Apple iPhone 11 Pro Max has 64GB 4GB RAM, 256GB 4GB RAM, 512GB 4GB RAM of built-in memory. This device has a Apple A13 Bionic (7 nm+) chipset. The main screen size is displaysize6.5 inches, 102.9 cm2 with 1242 x 2688 pixels, 19.5:9 ratio resolution. It has a 458 ppi density) ppi pixel density. The screen covers about 83.7% of the device's body. This screen to body ratio is a very impressive ALL VERSIONS A2218A2161A2220 Versions: A2218 (Global market) A2161 (USA, Canada, Puerto Rico, U.S. Virgin Islands) A2220 (China, Hong Kong)", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.virginmedia.com%2Fcontent%2Fdam%2Fvirginmedia%2Fdotcom%2Fimages%2Fmobile-browse%2FApple%2Fiphone-11-pro-max%2Fspace-grey%2FiPhone11-ProMAX-space-grey-back.png&f=1&nofb=1", price = 1350, review = 0, manufacturer =  m2});
            context.Phones.AddOrUpdate(new Phone { name = "iPhone XS", description = "Apple iPhone XS supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is September 2018. The device is working on an iOS 12 with a Hexa-core processor and 4 GB RAM memory. Apple iPhone XS has 64/256/512 GB of internal memory. This device has a Apple A12 Bionic chipset. The main screen size is displaysize5.8 inches, 84.4 cm2 with 1125 x 2436 pixels, 19.5:9 ratio resolution. It has a 458 ppi density) ppi pixel density. The screen covers about 82.9% of the device's body. This screen to body ratio is a very impressive", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fazfon.ae%2Fimage%2Fcache%2Fcatalog%2Fproduct%2F1all%2Fphone%2Fapple%2Fxss%2FGold%2Ffrn-1200x1200.png&f=1&nofb=1", price = 600, review = 0, manufacturer =  m2});
            context.Phones.AddOrUpdate(new Phone { name = "iPhone 8", description = "Apple iPhone 8 Plus supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is September 2017. The device is working on an iOS 11 with a Hexa-core (2x Monsoon + 4x Mistral) processor and 3 GB RAM memory. Apple iPhone 8 Plus has 64/256 GB of internal memory. This device has a Apple A11 Bionic chipset. The main screen size is 5.5 inches with 1080 x 1920 pixels resolution. It has a 401 ppi pixel density. The screen covers about 67.4% of the device's body. The result is quite good.", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fswitch.com.my%2Fwp-content%2Fuploads%2F2017%2F11%2Fiphone8_family-1.png&f=1&nofb=1", price = 380, review = 0, manufacturer = m2 });
            context.Phones.AddOrUpdate(new Phone { name = "S61", description = "Cat S61 supports frequency bands GSM , HSPA , LTE. Official announcement date is February 2018. The device is working on an Android 8.0 (Oreo) with a Octa-core 2.2 GHz Cortex-A53 processor and 4 GB RAM memory. Cat S61 has 64 GB of internal memory. This device has a Qualcomm SDM630 Snapdragon 630 chipset. The main screen size is displaysize5.2 inches, 74.5 cm2 with 1080 x 1920 pixels, 16:9 ratio resolution. It has a 424 ppi density) ppi pixel density. The screen covers about 65.4% of the device's body. The result is quite good.", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.catphones.com%2Ffr-fr%2Fwp-content%2Fuploads%2F2018%2F10%2Fs61-front.png&f=1&nofb=1", price = 425, review = 0, manufacturer = m3 });
            context.Phones.AddOrUpdate(new Phone { name = "P SMART Z", description = "Huawei P smart supports frequency bands GSM , HSPA , LTE. Official announcement date is December 2017. The device is working on an Android 8.0 (Oreo) with a Octa-core (4x2.36 GHz Cortex-A53 & 4x1.7 GHz Cortex-A53) processor. Huawei P smart has 64 GB, 4 GB RAM or 32 GB, 3 GB RAM of built-in memory. This device has a HiSilicon Kirin 659 chipset. The main screen size is displaysize5.65 inches, 82.4 cm2 with 1080 x 2160 pixels, 18:9 ratio resolution. It has a 427 ppi density) ppi pixel density. The screen covers about 76.1% of the device's body. This screen to body ratio is a very impressive Also called Huawei Enjoy 7S for China FIG-LX1, FIG-LA1, FIG-LX2, FIG-LX3 models have single sim and dual sim versions", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.bestmobil.sk%2Ffotky22187%2Ffotos%2F_vyr_2169Huawei-P-Smart-Z-Dual-Sim-Sapphire-Blue.png&f=1&nofb=1", price = 220, review = 0, manufacturer = m4 });
            context.Phones.AddOrUpdate(new Phone { name = "P30 Pro", description = "Huawei P30 Pro supports frequency bands GSM , HSPA , LTE. Official announcement date is March 2019. The device is working on an Android 9.0 (Pie); EMUI 9.1 with a Octa-core (2x2.6 GHz Cortex-A76 & 2x1.92 GHz Cortex-A76 & 4x1.8 GHz Cortex-A55) processor. Huawei P30 Pro has 128/256/512 GB, 8 GB RAM or 128 GB, 6 GB RAM of built-in memory. This device has a HiSilicon Kirin 980 (7 nm) chipset. The main screen size is displaysize6.47 inches, 102.8 cm2 with 1080 x 2340 pixels, 19.5:9 ratio resolution. It has a 398 ppi density) ppi pixel density. The screen covers about 88.6% of the device's body. This screen to body ratio is a very impressive ALL VERSIONS VOG-L04VOG-L09VOG-L29 Versions: VOG-L29, VOG-L09, VOG-L04 (Global); VOG-AL00, VOG-TL00 (China)", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fconsumer-img.huawei.com%2Fcontent%2Fdam%2Fhuawei-cbg-site%2Fcommon%2Fmkt%2Flist-image%2Fphones%2Fp30-pro%2FP30Pro_skyblue.png&f=1&nofb=1", price = 890, review = 0, manufacturer = m4});
            context.Phones.AddOrUpdate(new Phone { name = "P30 Lite", description = "Huawei P30 lite supports frequency bands GSM , HSPA , LTE. Official announcement date is March 2019. The device is working on an Android 9.0 (Pie), EMUI 9.0 with a Octa-core (4x2.2 GHz Cortex-A73 & 4x1.7 GHz Cortex-A53) processor and 6 GB RAM memory. Huawei P30 lite has 128 GB of internal memory. This device has a Hisilicon Kirin 710 (12 nm) chipset. The main screen size is displaysize6.15 inches, 93.6 cm2 with 1080 x 2312 pixels resolution. It has a 415 ppi density) ppi pixel density. The screen covers about 84.2% of the device's body. This screen to body ratio is a very impressive", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.91-cdn.com%2Fpricebaba-blogimages%2Fwp-content%2Fuploads%2F2019%2F04%2FHuawei-P30-Lite.png&f=1&nofb=1", price = 350, review = 0, manufacturer = m4});
            context.Phones.AddOrUpdate(new Phone { name = "Mate 20 Pro", description = "Huawei Mate 20 Pro supports frequency bands GSM , HSPA , LTE. Official announcement date is October 2018. The device is working on an Android 9.0 (Pie) with a Octa-core (2x2.6 GHz Cortex-A76 & 2x1.92 GHz Cortex-A76 & 4x1.8 GHz Cortex-A55) processor. Huawei Mate 20 Pro has 256 GB, 8 GB RAM or 128 GB, 6 GB RAM of built-in memory. This device has a HiSilicon Kirin 980 (7 nm) chipset. The main screen size is displaysize6.39 inches, 100.2 cm2 with 1440 x 3120 pixels, 19.5:9 ratio resolution. It has a 538 ppi density) ppi pixel density. The screen covers about 87.9% of the device's body. This screen to body ratio is a very impressive", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftshop.r10s.com%2Ffaf%2Fb3c%2F6244%2F1121%2F806a%2Fdce3%2F76b0%2F1161e88d7cc454448913e3.png&f=1&nofb=1", price = 690, review = 0, manufacturer = m4});
            context.Phones.AddOrUpdate(new Phone { name = "One Action", description = "The latest product of Motorola (Motorola One Action) was launched on 16th August 2019. Powered by a 2.2GHz octa-core Samsung Exynos 9609, it comes with a 6.30-inch touchscreen display with a resolution of 1080 x 2520 pixels and an aspect ratio of 21:9.", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.androidpolice.com%2Fwp-content%2Fuploads%2F2019%2F08%2FCopy-of-Motorola-One-Action-ROW-White-LAYDOWN-COMBO.png&f=1&nofb=1", price = 260, review = 0, manufacturer = m6});
            context.Phones.AddOrUpdate(new Phone { name = "2.2", description = "Nokia 2.2 is the new low price Nokia Android smartphone 2019. This new Nokia smartphone has a 13 MP back camera and 5 MP selfie camera. Let’s see the full specifications of this latest Nokia smartphone 2019.", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.movilzona.es%2Fapp%2Fuploads%2F2019%2F08%2FNokia-2.2-sin-fondo.png&f=1&nofb=1", price = 160, review = 0, manufacturer = m8 });
            context.Phones.AddOrUpdate(new Phone { name = "Galaxy S10e", description = "Samsung Galaxy S10e supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is February 2019. The device is working on an Android 9.0 (Pie); One UI with a Octa-core (2x2.7 GHz Mongoose M4 & 2x2.3 GHz Cortex-A75 & 4x1.9 GHz Cortex-A55) - EMEAOcta-core (1x2.8 GHz Kryo 485 & 3x2.4 GHz Kryo 485 & 4x1.7 GHz Kryo 485) - USA/LATAM, China processor. Samsung Galaxy S10e has 256 GB, 8 GB RAM or 128 GB, 6 GB RAM of built-in memory. This device has a Exynos 9820 Octa (8 nm) - EMEAQualcomm SDM855 Snapdragon 855 (7 nm) - USA/LATAM, China chipset. The main screen size is displaysize5.8 inches, 82.8 cm2 with 1080 x 2280 pixels, 19:9 ratio resolution. It has a 438 ppi density) ppi pixel density. The screen covers about 83.3% of the device's body. This screen to body ratio is a very impressive", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.theandroidsoul.com%2Fwp-content%2Fuploads%2F2019%2F01%2FSamsung-Galaxy-S10e-Canary-Yellow.png&f=1&nofb=1", price = 380, review = 0, manufacturer = m9 });
            context.Phones.AddOrUpdate(new Phone { name = "Galaxy Note10+", description = "Samsung Galaxy Note10+ supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is August 2019. The device is working on an Android 9.0 (Pie); One UI with a Octa-core (2x2.73 GHz Mongoose M4 & 2x2.4 GHz Cortex-A75 & 4x1.9 GHz Cortex-A55) - EMEA/LATAMOcta-core (1x2.84 GHz Kryo 485 & 3x2.42 GHz Kryo 485 & 4x1.78 GHz Kryo 485) - USA/China processor and 512GB 12GB RAM memory. Samsung Galaxy Note10+ has 256GB 12GB RAM of internal memory. This device has a Exynos 9825 (7 nm) - EMEA/LATAMQualcomm SDM855 Snapdragon 855 (7 nm) - USA/China chipset. The main screen size is displaysize6.8 inches, 114.0 cm2 with 1440 x 3040 pixels, 19:9 ratio resolution. It has a 498 ppi density) ppi pixel density. The screen covers about 91.0% of the device's body. This screen to body ratio is a very impressive ALL VERSIONS SM-N975FSM-N975F/DSSM-N975USM-N975U1SM-N975WSM-N9750/DSSM-N975N Versions: SM-N975F (Europe); SM-N975F/DS (Global); SM-N975U (USA); SM-N975U1 (USA unlocked); SM-N975W (Canada); SM-N9750/DS (LATAM, Brazil, China); SM-N975N (South Korea) Also called Samsung Galaxy Note10 Pro", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.androidbeat.com%2Fwp-content%2Fuploads%2F2019%2F08%2FGalaxy-Note10.png&f=1&nofb=1", price = 1550, review = 0, manufacturer = m9 });
            context.Phones.AddOrUpdate(new Phone { name = "Galaxy S10", description = "Samsung Galaxy S10 supports frequency bands GSM , CDMA , HSPA , EVDO , LTE. Official announcement date is February 2019. The device is working on an Android 9.0 (Pie); One UI with a Octa-core (2x2.7 GHz Mongoose M4 & 2x2.3 GHz Cortex-A75 & 4x1.9 GHz Cortex-A55) - EMEAOcta-core (1x2.8 GHz Kryo 485 & 3x2.4 GHz Kryo 485 & 4x1.7 GHz Kryo 485) - USA/LATAM, China processor and 8 GB RAM memory. Samsung Galaxy S10 has 128/512 GB of internal memory. This device has a Exynos 9820 Octa (8 nm) - EMEAQualcomm SDM855 Snapdragon 855 (7 nm) - USA/LATAM, China chipset. The main screen size is displaysize6.1 inches, 93.2 cm2 with 1440 x 3040 pixels, 19:9 ratio resolution. It has a 550 ppi density) ppi pixel density. The screen covers about 88.3% of the device's body. This screen to body ratio is a very impressive", img = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages.samsung.com%2Fis%2Fimage%2Fsamsung%2Fp5%2Fth%2Fgalaxy-s10%2Fpcd%2Ffeature_benefit_kv_galaxy_s10plus_prism_white.png%3F%24ORIGIN_PNG%24&f=1&nofb=1", price = 600, review = 0, manufacturer = m9 });




        }
    }
}
